<?php

namespace Hautzi\SystemMailBundle\Twig\Node;

use Twig_Compiler;

/**
 * EmailNode
 *
 * @author Christoph Nißle <derstoffel@posteo.de>
 */
class EmailNode extends \Twig_Node
{
    public function __construct(array $nodes = array(), array $attributes = array(), $lineno = 0, $tag = 'email')
    {
        parent::__construct($nodes, $attributes, $lineno, $tag);
    }

    public function compile(Twig_Compiler $compiler)
    {
        parent::compile($compiler); // TODO: Change the autogenerated stub
    }

}
 